export enum ProofTaskType {
    SALE_BATCH_MERGE = 0,

    PRESALE_CONTRACT_MAINTAIN_CONTRIBUTORS = 1,
    FAIRSALE_CONTRACT_MAINTAIN_CONTRIBUTORS = 2,
    PRIVATESALE_CONTRACT_MAINTAIN_CONTRIBUTORS = 3,

    CLIENT_AIRDROP_PROOF_REQ = 4,
    CLIENT_PRESALE_CONTRIBUTE_PROOF_REQ = 5,
    CLIENT_PRESALE_CLAIM_TOKEN_PROOF_REQ = 6,
    CLIENT_PRESALE_REDEEM_FUND_PROOF_REQ = 7,

    CLIENT_FAIRSALE_CONTRIBUTE_PROOF_REQ = 8,
    CLIENT_FAIRSALE_CLAIM_TOKEN_PROOF_REQ = 9,

    CLIENT_PRIVATESALE_CLAIM_PROOF_REQ = 10,
    CLIENT_PRIVATESALE_CONTRIBUTE_PROOF_REQ = 11,
    CLIENT_PRIVATESALE_REDEEM_FUND_PROOF_REQ = 12,

}

export interface ProofTaskDto<S, T> {
    taskType: ProofTaskType,
    index: S
    payload: T
}
